services:
  db:
    image: postgres:15
    container_name: moyeo-db

    environment:
      POSTGRES_DB: moyeo
      POSTGRES_USER: moyeo
      POSTGRES_PASSWORD: moyeo123

    ports:
      - "5433:5432"

    volumes:
      - moyeo_db:/var/lib/postgresql/data

volumes:
  moyeo_db:
